drop table chatroom_users;
drop table chatroom;
drop table event;
drop table user;

CREATE TABLE USER (
USER_ID INT PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(255)
);

CREATE TABLE CHATROOM (
CHATROOM_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(255)
);

CREATE TABLE CHATROOM_USERS (
CHATROOM_USERS_ID INT PRIMARY KEY AUTO_INCREMENT,
CHATROOM_ID INT,
USER_ID INT,
FOREIGN KEY (CHATROOM_ID) 
    REFERENCES CHATROOM(CHATROOM_ID),
FOREIGN KEY (USER_ID) 
    REFERENCES USER(USER_ID)
);

CREATE TABLE EVENT( 
EVENT_ID INT PRIMARY KEY AUTO_INCREMENT,
CHATROOM_ID INT,
EVENT_TYPE VARCHAR(255),
USER_ID INT,
COMMENT VARCHAR(255),
TIMESTAMP TIMESTAMP,
ALT_USER_ID INT,
FOREIGN KEY (CHATROOM_ID) 
    REFERENCES CHATROOM(CHATROOM_ID),
FOREIGN KEY (USER_ID) 
    REFERENCES USER(USER_ID),
FOREIGN KEY (ALT_USER_ID) 
    REFERENCES USER(USER_ID)
);